# Generated by Django 3.2.8 on 2021-11-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_auto_20211109_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='author',
        ),
    ]
