# Generated by Django 3.2.8 on 2021-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_remove_poem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
