# Generated by Django 3.2.8 on 2021-11-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_poem_poet'),
    ]

    operations = [
        migrations.CreateModel(
            name='poet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='poem',
            name='poet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.poet'),
        ),
    ]
