# Generated by Django 3.2.8 on 2021-11-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_auto_20211109_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poet',
            old_name='title',
            new_name='poet',
        ),
    ]
