# Generated by Django 3.2.8 on 2021-11-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_rename_title_poet_poet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poet',
            old_name='poet',
            new_name='poeti',
        ),
    ]
