# Generated by Django 3.2.8 on 2021-11-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0007_rename_poet_poet_poeti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poet',
            old_name='poeti',
            new_name='poet',
        ),
        migrations.AddField(
            model_name='poem',
            name='poeti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.poet'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poet',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
