# Generated by Django 3.2.8 on 2021-11-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0009_auto_20211109_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.poet'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='poet',
            field=models.CharField(max_length=200),
        ),
    ]
