# Generated by Django 3.2.8 on 2021-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0011_auto_20211111_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
