# Generated by Django 3.2.8 on 2021-11-12 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0013_alter_poem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poet_poet', to='poem.poet'),
        ),
    ]
